### ISSUE TITLE
// FIXME: prevent Swift bug, lazy property initialized twice from `init(coder:)`

### ISSUE THREAD

**Issue by walsht** [jessesquires/JSQWebViewController#12] opened 2016-01-13 19:21 UTC
When will this be corrected?

// FIXME: prevent Swift bug, lazy property initialized twice from `init(coder:)`

**Comment by jessesquires** [comment] 2016-01-13 19:44
![img](https://media.giphy.com/media/s1jJE4zTForZu/giphy.gif)

As the comment notes, this is a workaround for a bug in Swift.

To be clear, this library works around the issue — so it's safe to use.

There's a [rdar://22302280](https://openradar.appspot.com/radar?id=5037341588586496) opened for it.

**Comment by walsht** [comment] 2016-01-13 19:59
I am getting this crash on launching the web view more than one time...any idea?

objc[88037]: Cannot form weak reference to instance (0x7fba30cd7020) of class JSQWebViewController. It is possible that this object was over-released, or is in the process of deallocation.

**Comment by jessesquires** [comment] 2016-01-13 22:50
Hm... this sounds like the issue is with your references to the `JSQWebViewController` instance -- not related to the `FIXME:`

**Comment by jessesquires** [comment] 2016-04-07 05:34
**Update:** Still happens in Xcode 7.3 and Swift 2.2.

**Comment by jessesquires** [comment] 2017-08-03 21:47
Ah. got a fix for this:

> **Apple Developer Relations**
>
> August 3 2017, 6:49 AM
>
> This issue behaves as intended based on the following:  What you're seeing doesn't have anything to do with init(coder:).   Instead, the problem is that your implementation of the lazy value for _webView is re-entrant: it refers to self.view, which ends up calling viewDidLoad, which gets back to _webView and notices it hasn't been initialized yet.   It's only coincidence that in the "Push" and "Modal" cases 'view' has already been loaded before 'webView' is accessed.  Please update your bug report to let us know if this is still an issue for you.

So, we should be able to check `isViewLoaded` before initializing the WebView.

**Comment by jessesquires** [comment] 2017-09-22 16:06
Fixed for 6.0

**Closed as completed by jessesquires** 2017-09-22 16:06 UTC
Labels: bug, question
